---

- name: Ensure that plex directories are present
  become: True
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ plex_uid }}"
    group: "{{ plex_gid }}"
  with_items:
    - "{{ plex_db_dir }}"
    - "{{ plex_transcode_dir }}"

- name: Pull plexinc/pms-docker image
  docker_image:
    name: plexinc/pms-docker
    pull: True

- name: Create plex container
  docker_container:
    name: "{{ plex_container_name }}"
    image: plexinc/pms-docker
    state: started
    network_mode: host
    volumes:
      - "{{ plex_db_dir }}:/config"
      - "{{ plex_transcode_dir }}:/transcode"
      - "{{ plex_media_dir }}:/data"
    env: {TZ: "{{ plex_timezone }}", PLEX_CLAIM: "{{ plex_claim_token }}"}
